### ISSUE TITLE
cant install on colab

### ISSUE THREAD

**Issue by RoguePower** [binary-com/python-deriv-api#14]
When I try to pip install the following error is encountered, the command and the error are as follows:
**Command**
!python3 -m pip install python_deriv_api
!pip install python_deriv_api

**Result**
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement python_deriv_api (from versions: none)
ERROR: No matching distribution found for python_deriv_api

**Comment by chylli-deriv** [comment]
python_deriv_api need python version >= 3.9.6, but the version on colab is 3.8.10, which can't meet the requirement.
