### ISSUE TITLE
It doesn't do nothing

### ISSUE THREAD

**Issue by JhonAndersonVelasco** [binary-com/python-deriv-api#15]
I makethe first lines:
```
api = DerivAPI(app_id=app_id)
print (api)
```

Get the object:
`<deriv_api.deriv_api.DerivAPI object at 0x0000022AF7504280>`

And nothing more happens!

I am using simple_bot4.py from samples folder

**Comment by azataiot** [comment]
API is a Python object, what you want to get by just printing it out?

**Comment by JhonAndersonVelasco** [comment]
Sure, I know it's an object

I solved it doing a downgrade to python 3.9.13
