### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by JhonAndersonVelasco** [binary-com/python-deriv-api#6]
Hi

I am trying install with command:

`C:\Users\Jhon>pip install python_deriv_api`

And get:

`ERROR: Could not find a version that satisfies the requirement python_deriv_api (from versions: none)
ERROR: No matching distribution found for python_deriv_api`

Can you help me?

**Comment by azataiot** [comment]
> Hi
> 
> I am trying install with command:
> 
> `C:\Users\Jhon>pip install python_deriv_api`
> 
> And get:
> 
> `ERROR: Could not find a version that satisfies the requirement python_deriv_api (from versions: none) ERROR: No matching distribution found for python_deriv_api`
> 
> Can you help me?

which OS and Python version are you using? Are you installing it on Windows or Mac or Linux?

**Comment by matheusrrocha** [comment]
I'm having the same issue using mac os 12.3.1 (chip M1), python 3.9.12 and pip 22.1 (fresh installed)

**Comment by raunakkathuria** [comment]
It will be fixed with https://github.com/binary-com/python-deriv-api/pull/7

**Comment by raunakkathuria** [comment]
The #7 is merged. Closing this

**Comment by HopmanWorld** [comment]
ERROR Messages from " pip install python-deriv-api "

(base) C:\Users\Emmanuel>pip install python-deriv-api
WARNING: Ignoring invalid distribution -uture (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -uture (c:\programdata\anaconda3\lib\site-packages)
ERROR: Could not find a version that satisfies the requirement python-deriv-api (from versions: none)
ERROR: No matching distribution found for python-deriv-api
WARNING: Ignoring invalid distribution -uture (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -uture (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -uture (c:\programdata\anaconda3\lib\site-packages)
